" using Pathogen
call pathogen#infect()
" No Compatible mode
set nocompatible

" Enable UTF-8 Support
if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

" general vim settings
set textwidth=78
set tabstop=4
set shiftwidth=4
set expandtab
set relativenumber
set cursorline
set ruler
set spelllang=de
set spell
syntax on
filetype plugin indent on

" Font selection for different plattforms
if has("gui_running")
    if has("gui_gtk2")
    :set guifont=Luxi\ Mono\ 12
    elseif has("x11")
    " Also for GTK 1
    :set guifont=*-lucidatypewriter-medium-r-normal-*-*-180-*-*-m-*-*
    elseif has("gui_win32")
    :set guifont=Source_Code_Pro_Semibold:h10
    endif
endif

" Haskell Mode
au BufEnter *.hs compiler ghc
let g:haddock_browser="\"C:/Program Files (x86)/Mozilla Firefox/firefox.exe\""
let g:ghc="\"C:/Program Files (x86)/Haskell Platform/2012.2.0.0/bin/ghc.exe\""
let g:haddock_docdir="C:/Program\ Files\ (x86)/Haskell\ Platform/2012.2.0.0/doc/html/" 

" VimWiki
let wiki_1 = {}
let wiki_1.path          = '~\vimwiki\text'
let wiki_1.path_html     = '~\vimwiki\html'
let wiki_1.template_path = '~\vimwiki\templates'
let wiki_1.template_default = 'default'
let wiki_1.auto_export   = 1

let g:vimwiki_list = [wiki_1]
