call pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on

set textwidth=78
set tabstop=4
set shiftwidth=4
set expandtab
set relativenumber
set cursorline

if has("gui_running")
    if has("gui_gtk2")
    :set guifont=Luxi\ Mono\ 12
    elseif has("x11")
    " Also for GTK 1
    :set guifont=*-lucidatypewriter-medium-r-normal-*-*-180-*-*-m-*-*
    elseif has("gui_win32")
    :set guifont=Source_Code_Pro_Semibold:h10
    endif
endif
