" No Compatible mode
set nocompatible


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" initializing vundle                                                  "

filetype off " 

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

" It's required to let vundle manage vundle
Bundle 'gmarik/vundle'

" And here my custom bundles managed by vundle
Bundle 'https://github.com/chrisbra/histwin.vim'
Bundle 'https://github.com/msanders/snipmate.vim'
Bundle 'https://github.com/scrooloose/nerdcommenter'
Bundle 'https://github.com/scrooloose/nerdtree'
Bundle 'https://github.com/lukerandall/haskellmode-vim'
Bundle 'https://github.com/vim-ruby/vim-ruby'
Bundle 'taglist.vim'

"                                                                      "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Enable UTF-8 Support
if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

" general vim settings
syntax on
filetype plugin indent on " I need this, and vundle does to ;)
set textwidth=72
set tabstop=4
set shiftwidth=4
set expandtab
set relativenumber
set cursorline
set ruler
set spelllang=de
set spell
set ignorecase
set smartcase
set guioptions-=m " Remove the gui menu
set guioptions-=T " Remove the gui toolbar
set guioptions-=r " Remove right scrollbar
set guioptions-=L " Remove the conditional left scrollbar

" Font selection for different plattforms
if has("gui_running")
    if has("gui_gtk2")
    :set guifont="Source Code Pro Semi-Bold 10"
    elseif has("x11")
    " Also for GTK 1
    :set guifont=*-lucidatypewriter-medium-r-normal-*-*-180-*-*-m-*-*
    elseif has("gui_win32")
    :set guifont=Source_Code_Pro_Semibold:h10
    endif
endif

" Haskell Mode
"au BufEnter *.hs compiler ghc
"let g:haddock_browser="\"C:/Program Files (x86)/Mozilla Firefox/firefox.exe\""
"let g:ghc="\"C:/Program Files (x86)/Haskell Platform/2012.2.0.0/bin/ghc.exe\""
"let g:haddock_docdir="C:/Program\ Files\ (x86)/Haskell\ Platform/2012.2.0.0/doc/html/" 

" VimWiki
let wiki_1 = {}
let wiki_1.path          = '~\vimwiki\text'
let wiki_1.path_html     = '~\vimwiki\html'
let wiki_1.template_path = '~\vimwiki\templates'
let wiki_1.template_default = 'default'
let wiki_1.auto_export   = 1

let g:vimwiki_list = [wiki_1]
